<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Array_by_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ZEROS**


In [ ]:
import numpy as np
a = np.zeros((3,4))
print(a)
print(a.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


**ONES**

In [ ]:
ar_ones = np.ones((3,4))
print(ar_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


EMPTY

In [ ]:
ar_empty = np.empty((4))
print(ar_empty)

[4.73550817e-315 0.00000000e+000 6.52334991e-310 4.73039848e-315]


**RANGE**

In [ ]:
ar_range = np.arange(10)
print(ar_range)

[0 1 2 3 4 5 6 7 8 9]


**DIAGONAL FILLED WITH 1's**

In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_di = np.eye(3,4)
print(ar_di)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**LINE SPACE**

In [ ]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


**SUM OF ARRAY ELEMENT**

In [ ]:
import numpy as np
arr=((3,4,1,2,5))
a = np.sum(arr)
print(a)

15


**Mean**

In [ ]:
a=np.mean(arr)
print(a)

3.0


**Median**

In [ ]:
n = np.median(arr)
print(n)

3.0


**Minimum Value**

In [ ]:
a = np.min(arr)
print(a)

1


**Maximum Value**

In [ ]:
a = np.max(arr)
print(a)

5


**Standard Deviation**

In [ ]:
a =  np.std(arr)
print(a)

1.4142135623730951


Reshaping Arrays

In [ ]:
a = np.reshape(arr, (-1, 1))
print(a)

[[3]
 [4]
 [1]
 [2]
 [5]]


**Sorting**

In [ ]:
a = np.sort(arr)
print(a)

[1 2 3 4 5]


**Boolean Indexing**

In [ ]:
grades = np.array([85, 90, 78, 92, 88])
a = grades[grades >= 3]
print(a)

[85 90 78 92 88]


**Finding Indeces**

In [ ]:
a = np.where(grades >= 88)
print(a)

(array([1, 3, 4]),)
