<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Array_Creation_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Creation**

**1. np.array()**

In [2]:
import numpy as np
arr = ([1,2,3,4])
a = np.array(arr)
print(a)

[1 2 3 4]


**2. np.zeros()**

In [3]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


**3. np.ones()**

In [6]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


**4. np.full()**

In [7]:
arr = np.full(5,10)
print(arr)

[10 10 10 10 10]


**5. np.arrange**

In [8]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


**6. np.linespace()**

In [10]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


**7. np.eye**

In [12]:
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**8. np.diag()**

In [13]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
