<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Array_by_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ZEROS**


In [3]:
import numpy as np
a = np.zeros((3,4))
print(a)
print(a.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


**ONES**

In [4]:
ar_ones = np.ones((3,4))
print(ar_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


EMPTY

In [6]:
ar_empty = np.empty((4))
print(ar_empty)

[4.73550817e-315 0.00000000e+000 6.52334991e-310 4.73039848e-315]


**RANGE**

In [7]:
ar_range = np.arange(10)
print(ar_range)

[0 1 2 3 4 5 6 7 8 9]


**DIAGONAL FILLED WITH 1's**

In [8]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
ar_di = np.eye(3,4)
print(ar_di)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**LINE SPACE**

In [11]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
