<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Array_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### ✅ Array Attributes
**Definition**: Arrays have properties like shape, size, data type, and number of dimensions.

**Example & Code**:


In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)  # (2, 3)
print('Size:', arr.size)    # 6
print('Data type:', arr.dtype)  # int64 (or similar)
print('Dimensions:', arr.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Dimensions: 2


### ✅ Indexing and Slicing
**Definition**: Indexing accesses individual elements, while slicing extracts a portion of an array using `[start:stop:step]`.

**Example & Code**:


In [3]:
# 1D array
arr = np.array([5, 10, 15, 20, 25])
print('Element at index 2:', arr[2])  # 15
print('Slice 1 to 4:', arr[1:4])      # [10, 15, 20]

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print('Element at [0,1]:', arr2d[0, 1])  # 2
print('First row:', arr2d[0, :])         # [1, 2, 3]

Element at index 2: 15
Slice 1 to 4: [10 15 20]
Element at [0,1]: 2
First row: [1 2 3]


## 🔸 Basic Arithmetic Operations
**Definition**: Element-wise operations like addition (`+`), subtraction (`-`), multiplication (`*`), division (`/`), floor division (`//`), modulus (`%`), and exponentiation (`**`).

**Example & Code**:


In [5]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])
print('Addition:', x + y)          # [11, 22, 33]
print('Subtraction:', x - y)       # [9, 18, 27]
print('Multiplication:', x*y)    # [10, 40, 90]
print('Division:', x / y)          # [10., 10., 10.]
print('Floor Division:', x // y)   # [10, 10, 10]
print('Modulus:', x % y)           # [0, 0, 0]
print('Exponentiation:', x ** 2)   # [100, 400, 900]

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Floor Division: [10 10 10]
Modulus: [0 0 0]
Exponentiation: [100 400 900]


## 🔸 Universal Functions (ufuncs)
**Definition**: NumPy’s optimized functions for mathematical operations, applied element-wise (e.g., `np.sqrt`, `np.exp`, `np.sin`, `np.log`).

**Example & Code**:


In [6]:
arr = np.array([1, 4, 9])
print('Square root:', np.sqrt(arr))    # [1., 2., 3.]
print('Exponential:', np.exp(arr))     # [2.71828183, 54.59815003, 8103.08392758]
print('Sine:', np.sin(arr))            # [0.84147098, -0.7568025, 0.41211849]
print('Natural Log:', np.log(arr))     # [0., 1.38629436, 2.19722458]
print('Absolute:', np.abs([-1, 2, -3]))  # [1, 2, 3]
#%%
# More ufuncs
arr = np.array([1.2, 2.7, 3.5])
print('Ceiling:', np.ceil(arr))    # [2., 3., 4.]
print('Floor:', np.floor(arr))     # [1., 2., 3.]
print('Round:', np.round(arr))     # [1., 3., 4.]

Square root: [1. 2. 3.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
Sine: [ 0.84147098 -0.7568025   0.41211849]
Natural Log: [0.         1.38629436 2.19722458]
Absolute: [1 2 3]
Ceiling: [2. 3. 4.]
Floor: [1. 2. 3.]
Round: [1. 3. 4.]


## 🔸 Comparison and Logical Operations
**Definition**: Compare elements using operators (`==`, `!=`, `>`, `<`, `>=`, `<=`) or logical operations (`&`, `|`, `~`) to produce boolean arrays.

**Example & Code**:


In [7]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print('a > b:', a > b)          # [False, False, True]
print('a == b:', a == b)        # [False, True, False]
print('a != b:', a != b)        # [True, False, True]

# Logical operations
print('Logical AND:', (a > 1) & (a < 3))  # [False, True, False]
print('Logical OR:', (a < 2) | (a > 2))   # [True, False, True]
print('Logical NOT:', ~(a == 2))          # [True, False, True]
#%%
# Using np.where for conditional operations
arr = np.array([1, 2, 3, 4])
print('Where (replace > 2 with 0):', np.where(arr > 2, 0, arr))  # [1, 2, 0, 0]

a > b: [False False  True]
a == b: [False  True False]
a != b: [ True False  True]
Logical AND: [False  True False]
Logical OR: [ True False  True]
Logical NOT: [ True False  True]
Where (replace > 2 with 0): [1 2 0 0]



## 🔸 Aggregate Functions
**Definition**: Functions like `np.sum`, `np.mean`, `np.min`, `np.max`, `np.std` reduce arrays to a single value or compute statistics along an axis.

**Example & Code**:


In [8]:
data = np.array([1, 2, 3, 4, 5])
print('Sum:', np.sum(data))         # 15
print('Mean:', np.mean(data))       # 3.0
print('Min:', np.min(data))         # 1
print('Max:', np.max(data))         # 5
print('Standard Deviation:', np.std(data))  # 1.4142135623730951

Sum: 15
Mean: 3.0
Min: 1
Max: 5
Standard Deviation: 1.4142135623730951


In [9]:
# Aggregate functions with axis
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print('Sum along axis 0:', np.sum(arr2d, axis=0))  # [5, 7, 9]
print('Mean along axis 1:', np.mean(arr2d, axis=1))  # [2., 5.]

Sum along axis 0: [5 7 9]
Mean along axis 1: [2. 5.]


## 🔸 Reshaping Arrays
**Definition**: Change an array’s shape using `np.reshape()` or `.reshape()` without altering its data.

**Example & Code**:


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print('Reshaped to 2x3:\n', reshaped)

# Using -1 to infer dimension
reshaped_auto = arr.reshape(3, -1)
print('Reshaped with -1:\n', reshaped_auto)

Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
Reshaped with -1:
 [[1 2]
 [3 4]
 [5 6]]


## 🔸 Transpose of Array
**Definition**: Swap rows and columns using `.T` or `np.transpose()`.

**Example & Code**:


In [11]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print('Original:\n', mat)
print('Transpose:\n', mat.T)

# Using np.transpose
print('Transpose (np.transpose):\n', np.transpose(mat))

Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Transpose (np.transpose):
 [[1 4]
 [2 5]
 [3 6]]



## 🔸 Stacking Arrays
**Definition**: Combine arrays along a specified axis using `np.vstack()`, `np.hstack()`, or `np.concatenate()`.

**Example & Code**:


In [13]:
a = np.array([1, 2])
b = np.array([3, 4])
print('Vertical stack:\n', np.vstack((a, b)))
print('Horizontal stack:\n', np.hstack((a, b)))

# Stacking 2D arrays
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print('Concatenate along axis 0:\n', np.concatenate((c, d), axis=0))

Vertical stack:
 [[1 2]
 [3 4]]
Horizontal stack:
 [1 2 3 4]
Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 🔸 Splitting Arrays
**Definition**: Divide an array into multiple sub-arrays using `np.split()`, `np.vsplit()`, or `np.hsplit()`.

**Example & Code**:


In [14]:
arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr, 3)
print('Split into 3 parts:', split_arr)

# Splitting 2D array
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Vertical split:\n', np.vsplit(mat, 3))
print('Horizontal split:\n', np.hsplit(mat, 3))

Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]
Vertical split:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Horizontal split:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


## 🔸 Copy vs View
**Definition**: A `copy` creates a new, independent array, while a `view` shares the same data with the original array.

**Example & Code**:


In [15]:
original = np.array([1, 2, 3])
copy = original.copy()
view = original.view()
original[0] = 99
print('Original after change:', original)  # [99, 2, 3]
print('Copy:', copy)                      # [1, 2, 3]
print('View:', view)

Original after change: [99  2  3]
Copy: [1 2 3]
View: [99  2  3]



## 🔸 Broadcasting
**Definition**: Allows operations between arrays of different shapes by automatically expanding the smaller array’s dimensions.

**Example & Code**:


In [16]:
# Broadcasting with a scalar
a = np.array([1, 2, 3])
b = 2
print('a * 2:\n', a * b)  # [2, 4, 6]

# Broadcasting with arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
vec = np.array([10, 20, 30])
print('2D + 1D:\n', arr2d + vec)

a * 2:
 [2 4 6]
2D + 1D:
 [[11 22 33]
 [14 25 36]]


## 🔸 Matrix Operations
**Definition**: Perform linear algebra operations like dot product, matrix multiplication, and determinant.

**Example & Code**:


In [17]:
# Dot product
a = np.array([1, 2])
b = np.array([3, 4])
print('Dot product:', np.dot(a, b))  # 1*3 + 2*4 = 11

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Matrix multiplication:\n', np.matmul(A, B))

# Determinant
print('Determinant of A:', np.linalg.det(A))

Dot product: 11
Matrix multiplication:
 [[19 22]
 [43 50]]
Determinant of A: -2.0000000000000004
