<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Indexing%2CSlicing_and_Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indexing , Slicing and Reshaping**

**1. Indexing and slicing**

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = arr[2:7]
print(arr)

[3 4 5 6 7]


**2. np.shape()**

In [7]:
arr = np.array([[1,2,3,4,5,6,7,8,9],[27,223,])
print(arr.shape)

(9,)


**3. np.flatten()**

In [12]:
arr = ([[1,23,3,4]])
arr= np.array(arr)
arr = arr.flatten() # Call flatten() on the array object
print(arr)

[ 1 23  3  4]


**4. np.transpose()**

In [13]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
arr = np.transpose(arr)
print(arr)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**5. np.ravel()**

In [14]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
arr = arr.ravel()
print(arr)
#

[1 2 3 4 5 6 7 8 9]
