<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/Linear_Algebra(Matrix_Operations).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Algebra**

**1. Create a Matrix**

In [2]:
import numpy as np
m = np.array([[5,6],[7,8]])
print(m)

[[5 6]
 [7 8]]


**2. Transpose (np.transpose)**

In [3]:
arr = np.transpose(m)
print(arr)

[[5 7]
 [6 8]]


**3. Identify Matrix (np.eye(3).astype(int)**

In [7]:
arr = np.eye(5).astype(int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**4. Diagonal Element (np.diag)**

In [11]:
arr = np.diag(m)
print(arr)

[5 8]


**5. Diagonal Matrix Creation (np.diag)**

In [12]:
arr = np.diag([10,20,30])
print(arr)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


**6. Trace of Matrix**

In [13]:
arr = np.trace(m)
print(arr)

13


**7. Addition and Substraction**

In [15]:
B = np.array([[5,6],[7,8]])
print(m+B)
print(m-B)

[[10 12]
 [14 16]]
[[0 0]
 [0 0]]


**8. Element-Wise Multiplication**

In [16]:
print(m*B)

[[25 36]
 [49 64]]


**9. Dot Product(np.matmul(A,B))**

In [17]:
arr = np.matmul(m,B)
print(arr)

[[ 67  78]
 [ 91 106]]


**10. Determinant of Matrix(np.linalg.det(arr))**

In [18]:
arr = np.linalg.det(m)
print(arr)

-2.000000000000005


**11. Inverse (np.linalg.inv())**

In [19]:
arr = np.linalg.inv(m)
print(arr)

[[-4.   3. ]
 [ 3.5 -2.5]]


**12. Rank (np.linalg.matrix_rank())**

In [20]:
arr = np.linalg.matrix_rank(m)
print(arr)

2


**13. Solving Linear Equation**

In [21]:
arr = np.linalg.solve(m,B)
print(arr)

[[1.00000000e+00 0.00000000e+00]
 [3.10862447e-15 1.00000000e+00]]


**14. Eigen_Values and Eigen_Value**

In [22]:
arr = np.linalg.eig(m)
print(arr)

EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))


**15. Check if Matrix is Orthogonal**

In [23]:
q = np.array([[1,0],[0,-1]])
print(np.dot(q,q.T))

[[1 0]
 [0 1]]


**16. Check Positive Definitess**

In [27]:
def is_Positive_Definite(x):
  return np.all(np.linalg.eigvals(x) > 0)
print(is_Positive_Definite(m))

False
