<a href="https://colab.research.google.com/github/Kamalsharma209/NumPy-Practice/blob/main/NumPy_Array_with_Random_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Random**

**Rand-Function**:- genetrate random value between 0 to 1

In [1]:
import numpy as np
arr = np.random.rand(4)
print(arr)

[0.30783756 0.66066736 0.09296783 0.08804548]


**Randn-Function**:- generate random value close to zero and return positive and negative values as well.

In [2]:
arr = np.random.randn(4)
print(arr)

[ 0.81162932  0.50546824  2.31994888 -1.54948201]


**Randf-Function**:- fills with random floats in the half open interval[0.0,1.0).... not included 1..

In [3]:
arr = np.random.ranf(4)
print(arr)

[0.19978387 0.07964755 0.67499417 0.04427897]


**randint-Function**:- random numbers are given within user range

In [6]:
arr = np.random.randint(2,10,(3,4))
print(arr)

[[7 3 8 2]
 [3 8 3 3]
 [9 4 4 3]]
